/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package keleyrenan.pvdprojeto;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import java.util.Date;
import java.text.SimpleDateFormat;


/**
 *
 * @author rdias
 */
public class TelaVenda extends javax.swing.JFrame {
    ArrayList<String> Result = new ArrayList<String>();

    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        initComponents();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        InsCod = new javax.swing.JTextField();
        LocalizarBut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ProdutoNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InsQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MetoPaga = new javax.swing.JComboBox<>();
        VendaBut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        MostrarPreco = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Subtotal = new javax.swing.JLabel();
        SubtotalBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mercado Popular");

        InsCod.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        InsCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsCodActionPerformed(evt);
            }
        });

        LocalizarBut.setText("Localizar");
        LocalizarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocalizarButActionPerformed(evt);
            }
        });

        jLabel2.setText("Produto:");

        ProdutoNome.setText("....");

        jLabel3.setText("Quantidade:");

        InsQuantidade.setText("15");
        InsQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsQuantidadeActionPerformed(evt);
            }
        });

        jLabel4.setText("Método de Pagamento:");

        MetoPaga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão", "A Vista" }));
        MetoPaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetoPagaActionPerformed(evt);
            }
        });

        VendaBut.setText("Vender");
        VendaBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendaButActionPerformed(evt);
            }
        });

        jLabel5.setText("Preço por Unidade: ");

        MostrarPreco.setText("....");

        jLabel6.setText("Subtotal:");

        Subtotal.setText("....");

        SubtotalBut.setText("Subtotal");
        SubtotalBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtotalButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MetoPaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 270, Short.MAX_VALUE))
                            .addComponent(InsCod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LocalizarBut))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MostrarPreco))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InsQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProdutoNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SubtotalBut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Subtotal))
                            .addComponent(VendaBut))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocalizarBut))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ProdutoNome)
                    .addComponent(jLabel6)
                    .addComponent(Subtotal)
                    .addComponent(SubtotalBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MostrarPreco))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InsQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(MetoPaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(VendaBut)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LocalizarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocalizarButActionPerformed
        // TODO add your handling code here:
        String local = InsCod.getText();
        String lo = local + ".produto";
        
               
               
                
               
            
                
                
                try {
                FileInputStream fis = new FileInputStream(lo);
                ObjectInputStream ois = new ObjectInputStream(fis);
                Result = (ArrayList) ois.readObject();
                
                ois.close();
                fis.close();
                 
              
            
                }catch (IOException ioe){
                    JOptionPane.showMessageDialog(null, "Produto não encontrado!");
                    
                    
                }catch(ClassNotFoundException c){
                    JOptionPane.showMessageDialog(null, "Produto não encontrado!");
                    
                }
                
                System.out.print(Result);
                ProdutoNome.setText(Result.get(1));
                MostrarPreco.setText("R$"+Result.get(2));
                
                
    }//GEN-LAST:event_LocalizarButActionPerformed

    private void InsQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsQuantidadeActionPerformed

    private void MetoPagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetoPagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MetoPagaActionPerformed

    private void VendaButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendaButActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = new Date();
        try {
            FileOutputStream fos = new FileOutputStream("vendas.venda", true);
            
            Float ganho = Float.parseFloat(Result.get(2)) * Integer.parseInt(InsQuantidade.getText());
            String data = Result.get(1) + ", " + InsQuantidade.getText()+ " Unidade(s)" + ", " + "RS$"+ ganho + ", " + formatter.format(date) + ", " + MetoPaga.getSelectedItem() + System.lineSeparator();
            fos.write(data.getBytes());
            fos.close();
            JOptionPane.showMessageDialog(null, "Venda Feita!");
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado!");
        }
        
        //System.out.print(Result.get(4));
      /*  
        Path caminho = Paths.get(Result.get(0)+".produto"); 
        try {
            String conteudo = new String(Files.readAllBytes(caminho));
            //Int meno = 
            conteudo = conteudo.replace(Result.get(4),Integer.toString(Integer.parseInt(Result.get(4)) - Integer.parseInt(InsQuantidade.getText())) ); 
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Errooo!");;
        }
        */
        
        
        
        
        
        
    }//GEN-LAST:event_VendaButActionPerformed

    private void InsCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsCodActionPerformed

    private void SubtotalButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtotalButActionPerformed
        // TODO add your handling code here:
        Float ganho = Float.parseFloat(Result.get(2)) * Integer.parseInt(InsQuantidade.getText());
        Subtotal.setText("R$"+Float.toString(ganho));
        
    }//GEN-LAST:event_SubtotalButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InsCod;
    private javax.swing.JTextField InsQuantidade;
    private javax.swing.JButton LocalizarBut;
    private javax.swing.JComboBox<String> MetoPaga;
    private javax.swing.JLabel MostrarPreco;
    private javax.swing.JLabel ProdutoNome;
    private javax.swing.JLabel Subtotal;
    private javax.swing.JButton SubtotalBut;
    private javax.swing.JButton VendaBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
